config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "home#index"
  resources :settings, only: [:index] do
    collection do
      get :orders
      get :password
      patch :update_user
      patch :update_password
    end
  end

  resources :orders, only: [:new, :create, :show, :index]

  resources :addresses
  resources :carts, only: [:show, :create] do
    member do
      post "add_to_cart", to: "carts#add", as: "add_to_cart"
      post "update_cart", to: "carts#update_item", as: "update_cart"
      post "remove_from_cart", to: "carts#remove", as: "remove_cart_item"
      post "finalize_order", to: "orders#finalize", as: "finalize_order"
      get "show_items", to: "carts#show_items", as: "show_items"
    end
    collection do
      post :create
    end
  end

  namespace :admin do
    root to: "dashboard#index"
    resources :categories
    resources :products
    resources :users do
      member do
        post :toggle_admin
      end
    end
  end
end

=begin
 em controllers de MVC existe três tipos de actions(por deaful):
  - actions de coleção: index, new, create
  - actions de membro: show, edit, update, destroy 


  estudar sobre "soft delete"
=end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
  has_many :cart
  has_many :order
  validates :name, presence: true
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :orders, dependent: :destroy
  has_many :products, through: :orders

  validates :user, presence: true

  def total_price
    total = orders.order(:created_at).sum { |order| order.product&.price.to_f * order.quantity }
    Rails.logger.info "Total Price: #{total}"
    total
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, :position, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :cart
  belongs_to :product
  belongs_to :user

  belongs_to :status, optional: true
  belongs_to :payment_method, optional: true

  enum payment_method: { credit_card: :credit_card, paypal: :paypal }
  enum status: { awaiting_payment: :awaiting_payment, processing: :processing, done: :done }

  def total_price
    product.price * quantity
  end
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
  has_many :orders
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  before_destroy :purge_attached
  has_many :orders, dependent: :destroy
  has_many :carts, through: :orders
  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
    attachable.variant :big_thumb, resize_to_limit: [600, 700]
  end

  scope :published, -> { where(publish: true) }

  validates :name, :description, :price, presence: true
  validate :image_attached

  def image_link
    if self.image.attached?
      self.image.variant(resize_to_limit: [100, 100]).processed.url
    else
      "https://via.placeholder.com/100x100?text=Sem+imagem"
    end
  end

  after_save do
    instance = self.image
    folder = "products"
    name = "file"
    record_type = "Product"
    record_id = self.image.blob.id
    ImageService.save(instance, folder, name, record_type, record_id)
  end

  private

  def purge_attached
    image.purge if image.attached?
  end

  def image_attached
    errors.add(:image, "must be attached") unless image.attached?
  end
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :orders
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :phone, presence: true

  has_one_attached :avatar
  has_many :addresses, dependent: :destroy
  has_one :cart, dependent: :destroy
  has_many :orders, dependent: :destroy

  enum role: { user: "user", admin: "admin" }
end

app/models/user_admin.rb
class UserAdmin < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all.map { |product| ProductDecorator.new(product) }
    @cart = Cart.find_or_initialize_by(id: session[:cart_id])

    if @cart.new_record?
      @cart.save
      session[:cart_id] = @cart.id
    end
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :authenticate_user!
  helper ApplicationHelper

  def index
    @user = current_user
  end

  def update_user
    if current_user.update(user_params)
      flash[:success] = "Dados atualizados com sucesso"
      redirect_to settings_path
    else
      flash[:alert] = "Erro ao atualizar dados"
      render :index
    end
  end

  def update_password
    if !current_password_params[:current_password].blank? && current_user.valid_password?(current_password_params[:current_password])
      if current_user.update(password_params)
        bypass_sign_in(current_user)
        redirect_to settings_path, flash[:success] = "Senha atualizada com sucesso"
      else
        render :password
      end
    else
      flash[:alert] = "Digite sua senha atual"
      redirect_to password_settings_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :phone, :avatar)
  end

  def current_password_params
    params.require(:user).permit(:current_password)
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(type)
    case type
    when "success"
      "alert-success"
    when "error"
      "alert-danger"
    when "alert"
      "alert-warning"
    when "notice"
      "alert-info"
    else
      "alert-info"
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/user_admins_helper.rb
module UserAdminsHelper
end

app/helpers/user_helper.rb
module UserHelper
  def avatar_url(current_user)
    return current_user.avatar if current_user.avatar.attached?
    "profile"
  end
end

app/views/settings/_menu.html.erb
<ul class="list-group list-group-flush">
  <a href="<%= settings_path %>" class="menu-item-profile"><li class="list-group-item">Meu perfil</li></a>
  <a href="<%= password_settings_path %>" class="menu-item-profile"><li class="list-group-item">Alterar senha</li></a>
  <a href="<%= addresses_path %>" class="menu-item-profile"><li class="list-group-item">Endereços</li></a>
  <a href="<%= orders_path %>" class="menu-item-profile"><li class="list-group-item">Meus pedidos</li></a>
  <!--<a href="#" class="menu-item-profile"><li class="list-group-item">Produtos favoritos</li></a> -->
</ul>

app/views/settings/index.html.erb
<header class="bg-dark py-1">
  <div class="container px-5 px-lg-5 my-5">
    <div class="text-center text-white">
      <h1 class="display-8 fw-bolder">Sua loja virtual preferida</h1>
      <p class="lead fw-normal text-white-50 mb-0">Otprime, mexendo com sua cabeça</p>
    </div>
  </div>
</header>
<section class = "py-5">
  <div class = "container ">
    <div class="row">
      <div class="col-3">
        <div class="card">          
         <%= render "menu" %>
        </div>
      </div> 
      <div class="col-9">
        <div class="card">    
          <div class="card-body">    
              <%= render "layouts/shared/flash" if flash.present? %>  
            <h2> <%= current_user.name %></h2>            
            <%= image_tag avatar_url(current_user), width: 120, height: 120, class: "mb-4 rounded-circle" %>
            <%= simple_form_for current_user, url: update_user_settings_path do |f| %>
              <%= f.input :avatar, label: false, hint: "Escolha uma imagem para seu perfil", input_html: { class: "input_image_full" } %>
              <%= f.input :name, label: "Nome" %>
              <%= f.input :email, label: "E-mail", readonly: true %>              
              <%= f.input :phone, label: "Telefone", input_html: { class: "mask-phone" }, placeholder: "Telefone" %>                
              <%= f.button :submit, "Atualizar", class: "btn btn-outline-primary mt-4" %>
            <% end %>
          </div>
          
        </div>
      </div>    
    </div>
  </div>    
</section>

app/views/settings/password.html.erb
<header class="bg-dark py-1">
  <div class="container px-5 px-lg-5 my-5">
    <div class="text-center text-white">
      <h1 class="display-8 fw-bolder">Sua loja virtual preferida</h1>
      <p class="lead fw-normal text-white-50 mb-0">Otprime, mexendo com sua cabeça</p>
    </div>
  </div>
</header>
<section class="py-5">
  <div class="container">
    <div class="row">
      <div class="col-3">
        <div class="card">
          <%= render "menu" %>
        </div>
      </div>
      <div class="col-9">
        <div class="card">
          <div class="card-body">
            <%= render "layouts/shared/flash" if flash.present? %>
            <h2>Alterar senha</h2>
            <%= simple_form_for current_user, url: update_password_settings_path, data: { turbo: false } do |f| %>
              <%= f.input :current_password %>
              <%= f.input :password %>
              <%= f.input :password_confirmation %>
              <%= f.button :submit, "Atualizar senha", class: "btn btn-outline-primary mt-4" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>