config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "home#index"
  resources :settings, only: [:index] do
    collection do
      get :orders
      get :password
      patch :update_user
      patch :update_password
    end
  end

  resources :orders, only: [:new, :create, :show, :index]

  resources :addresses
  resources :carts, only: [:show, :create] do
    member do
      post "add_to_cart", to: "carts#add", as: "add_to_cart"
      post "update_cart", to: "carts#update_item", as: "update_cart"
      post "remove_from_cart", to: "carts#remove", as: "remove_cart_item"
      post "finalize_order", to: "orders#finalize", as: "finalize_order"
      get "show_items", to: "carts#show_items", as: "show_items"
    end
    collection do
      post :create
    end
  end

  namespace :admin do
    root to: "dashboard#index"
    resources :categories
    resources :products
    resources :users do
      member do
        post :toggle_admin
      end
    end
  end
end

=begin
 em controllers de MVC existe três tipos de actions(por deaful):
  - actions de coleção: index, new, create
  - actions de membro: show, edit, update, destroy 


  estudar sobre "soft delete"
=end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
  has_many :cart
  has_many :order
  validates :name, presence: true
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :orders, dependent: :destroy
  has_many :products, through: :orders

  validates :user, presence: true

  def total_price
    total = orders.order(:created_at).sum { |order| order.product&.price.to_f * order.quantity }
    Rails.logger.info "Total Price: #{total}"
    total
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, :position, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :cart
  belongs_to :product
  belongs_to :user

  belongs_to :status, optional: true
  belongs_to :payment_method, optional: true

  enum payment_method: { credit_card: :credit_card, paypal: :paypal }
  enum status: { awaiting_payment: :awaiting_payment, processing: :processing, done: :done }

  def total_price
    product.price * quantity
  end
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
  has_many :orders
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  before_destroy :purge_attached
  has_many :orders, dependent: :destroy
  has_many :carts, through: :orders
  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
    attachable.variant :big_thumb, resize_to_limit: [600, 700]
  end

  scope :published, -> { where(publish: true) }

  validates :name, :description, :price, presence: true
  validate :image_attached

  def image_link
    if self.image.attached?
      self.image.variant(resize_to_limit: [100, 100]).processed.url
    else
      "https://via.placeholder.com/100x100?text=Sem+imagem"
    end
  end

  after_save do
    instance = self.image
    folder = "products"
    name = "file"
    record_type = "Product"
    record_id = self.image.blob.id
    ImageService.save(instance, folder, name, record_type, record_id)
  end

  private

  def purge_attached
    image.purge if image.attached?
  end

  def image_attached
    errors.add(:image, "must be attached") unless image.attached?
  end
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :orders
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :phone, presence: true

  has_one_attached :avatar
  has_many :addresses, dependent: :destroy
  has_one :cart, dependent: :destroy
  has_many :orders, dependent: :destroy

  enum role: { user: "user", admin: "admin" }
end

app/models/user_admin.rb
class UserAdmin < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all.map { |product| ProductDecorator.new(product) }
    @cart = Cart.find_or_initialize_by(id: session[:cart_id])

    if @cart.new_record?
      @cart.save
      session[:cart_id] = @cart.id
    end
  end
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(type)
    case type
    when "success"
      "alert-success"
    when "error"
      "alert-danger"
    when "alert"
      "alert-warning"
    when "notice"
      "alert-info"
    else
      "alert-info"
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/user_admins_helper.rb
module UserAdminsHelper
end

app/helpers/user_helper.rb
module UserHelper
  def avatar_url(current_user)
    return current_user.avatar if current_user.avatar.attached?
    "profile"
  end
end

app/views/admin/caterogies/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>Position:</strong>
    <%= category.position %>
  </p>

</div>

app/views/admin/caterogies/_form.html.erb
<%= simple_form_for([:admin, @category]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :position %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Salvar", class: "btn btn-info" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Otprime Store</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="icon" href="<%= asset_path("image.png") %>" type="image/x-icon">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <style>
      body {
        display: flex;
        flex-direction: column;
        min-height: 100vh;
        margin: 0;
      }

      main {
        flex: 1;
      }

      footer {
        flex-shrink: 0;
      }
    </style>
  </head>
  <body>  
    <%= render "layouts/store/nav" %>  
    <main>
      <%= turbo_stream_from "new" %>
      <%= yield %>
    </main>  
    <%= render "layouts/store/footer" %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Otprime Store</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "devise", "data-turbo-track": "reload" %>
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
	  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= javascript_include_tag "devise", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <section class="ftco-section">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-6 text-center mb-5">
            <h2 class="heading-section"><%= link_to "Otprime Store", root_path %></h2>
          </div>
        </div>

        <div class="row justify-content-center">
          <div class="col-md-7 col-lg-5">
            <div class="login-wrap p-4 p-md-5">
              <div class="icon d-flex align-items-center justify-content-center">
                <span class="fa fa-user-o"></span>
              </div>
              <h3 class="text-center mb-4">Login</h3>
              <%= render "layouts/shared/flash" if flash.present? %>
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </section>
  </body>
</html>

app/views/layouts/shared/_flash.html.erb
<div class="alert alert-info text-center">
  <% flash.each do |type, msg| %>
    <div class="alert <%= flash_class(type) %> text-center">
      <%= msg %>
    </div>
  <% end %>
</div>

app/views/layouts/store/_footer.html.erb
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">
            Copyright &copy; Otprime Store - Todos os direitos reservados. 2023
            <br>
            Desenvolvido por um: 
            <br>
            Sem criatividade
        </p>
    </div>
</footer>

app/views/layouts/store/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container px-4 px-lg-5">            
            <%= image_tag "image.png", alt: "Logo", width: 50, height: 50, style: " margin-left: -90px " %> 
            <a class="navbar-brand" style="margin-left: 60px;" href="<%= root_path %>">Otprime Store</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">                              
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <!--
                    <li class="nav-link"><a class="nav-link active" aria-current="page" href="<%= root_path %>">Home</a></li>
                    <li class="nav-link"><a class="nav-link" href="#!">Meu perfil</a></li>
                    --->
                    <%= render "layouts/store/user_signed" %>
                </ul>       
                <% if current_user && current_user.cart.present? %>
                    <%= link_to "Carrinho", show_items_cart_path(current_user.cart.id), class: "btn btn-outline-dark" %>
                <% end %>
            </div>
        </div>
    </nav>        

app/views/layouts/store/_user_signed.html.erb
<% if user_signed_in? %>    
    <li class="nav-link">
        <%= link_to "Conta", settings_path, class: "nav-link" %>
    <li class="nav-link logout-button">
        <%= form_tag(destroy_user_session_path, method: :delete) do %>
            <%= submit_tag("Sair", class: "btn nav-link") %>
        <% end %>
  </li>     
<% else %>
    <li class="nav-link">              
        <%= link_to "Cadastre-se", new_user_registration_path, class: "nav-link" %>
    </li>
    <li class="nav-link">
        <%= link_to "Entrar", new_user_session_path, class: "nav-link" %>
    </li>                    
<% end %>