config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "home#index"
  resources :settings, only: [:index] do
    collection do
      get :orders
      get :password
      patch :update_user
      patch :update_password
    end
  end

  resources :orders, only: [:new, :create, :show, :index]

  resources :addresses
  resources :carts, only: [:show, :create] do
    member do
      post "add_to_cart", to: "carts#add", as: "add_to_cart"
      post "update_cart", to: "carts#update_item", as: "update_cart"
      post "remove_from_cart", to: "carts#remove", as: "remove_cart_item"
      post "finalize_order", to: "orders#finalize", as: "finalize_order"
      get "show_items", to: "carts#show_items", as: "show_items"
    end
    collection do
      post :create
    end
  end

  namespace :admin do
    root to: "dashboard#index"
    resources :categories
    resources :products
    resources :users do
      member do
        post :toggle_admin
      end
    end
  end
end

=begin
 em controllers de MVC existe três tipos de actions(por deaful):
  - actions de coleção: index, new, create
  - actions de membro: show, edit, update, destroy 


  estudar sobre "soft delete"
=end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :orders, dependent: :destroy
  has_many :products, through: :orders

  validates :user, presence: true

  def total_price
    total = orders.order(:created_at).sum { |order| order.product&.price.to_f * order.quantity }
    Rails.logger.info "Total Price: #{total}"
    total
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :add, :remove, :update_item]
  before_action :authenticate_user!

  def show
    @orders = @cart.orders.includes(:product)
    respond_to do |format|
      format.html
      format.turbo_stream { update_cart_stream }
    end
  end

  def create
    @cart = current_user.cart || current_user.build_cart
    @cart.attributes = cart_params

    if @cart.save
      product = Product.find(params[:cart][:id])
      order = @cart.orders.find_or_initialize_by(product: product)
      order.quantity += params[:cart][:quantity].to_i

      order.status = Status.find_by(name: params[:status])
      order.payment_method = PaymentMethod.find_by(name: params[:payment_method])

      if current_user
        order.user = current_user
      end

      if order.save
        flash[:success] = "Produto adicionado ao carrinho com sucesso!"
      else
        flash[:error] = "Erro ao adicionar o produto ao carrinho."
        Rails.logger.error "Order not saved. Errors: #{order.errors.full_messages}"
      end
    else
      flash[:error] = "Erro ao adicionar o produto ao carrinho."
    end

    redirect_to show_items_cart_path(@cart)
  end

  def add
    @product = Product.find_by(id: params[:id])
    quantity = params[:quantity].to_i
    @cart = current_user.cart || current_user.build_cart

    if quantity.positive? && @product
      current_order = @cart.orders.find_or_initialize_by(product_id: @product.id)

      payment_method_param = params[:payment_method]
      payment_method_sym = payment_method_param.present? ? payment_method_param.to_sym : nil

      current_order.assign_attributes(
        user: current_user,
        quantity: current_order.quantity.to_i + quantity,
        status: Status.find_or_create_by(name: :awaiting_payment),
        payment_method: payment_method_sym,
      )

      if current_order.save
        Rails.logger.info "Order saved: #{current_order.inspect}"
      else
        Rails.logger.error "Order not saved. Errors: #{current_order.errors.full_messages}"
      end
    elsif @product
      @cart.orders.find_by(product_id: @product.id)&.destroy
    end

    @cart.save if @cart.orders.any?

    respond_to do |format|
      format.html {
        redirect_to show_items_cart_url(@cart)
      }
      format.turbo_stream { update_cart_stream }
    end
  end

  def update_item
    @product = Product.find_by(id: params[:product_id])
    quantity = params[:quantity].to_i

    if quantity.positive? && @product
      current_order = @cart.orders.find_or_initialize_by(product_id: @product.id)
      current_order.update(quantity: quantity)
    elsif @product
      @cart.orders.find_by(product_id: @product.id)&.destroy
    end

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.replace("cart", partial: "cart/cart", locals: { cart: @cart }) }
    end
  end

  def remove
    @cart = Cart.find(params[:id])
    orders = @cart.orders
    order_to_remove = orders.find(params[:orders_id])

    order_to_remove.destroy

    respond_to do |format|
      if orders.count >= 1
        format.html { redirect_to show_items_cart_path(@cart), notice: "Item removido do carrinho." }
      else
        format.html { redirect_to root_path, notice: "Item removido do carrinho. Carrinho vazio." }
      end
      format.turbo_stream { remove_item_stream(order_to_remove) }
    end
  end

  private

  def set_cart
    @cart = Cart.find_by(id: params[:id])
  end

  def update_cart_stream
    turbo_stream.replace(
      "cart-frame",
      partial: "carts/cart",
      locals: { cart: @cart },
    )
  end

  def cart_params
    params.require(:cart).permit(:id, :quantity)
  end

  def remove_item_stream(order)
    turbo_stream.remove dom_id(order)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_address_table.html.erb
<% if @addresses.present? && @addresses.any? %>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Nome</th>
        <th scope="col">Rua</th>
        <th scope="col">Bairro</th>
        <th scope="col">Número</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @addresses.each do |address| %>
        <tr>
          <td><%= address.name %></td>
          <td><%= address.street %></td>
          <td><%= address.neighborhood %></td>
          <td><%= address.number %></td>
          <td>
            <%= link_to "Detalhes", address_path(address), class: "btn btn-secondary" %>                      
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <span style="font-size: smaller;">Nenhum endereço cadastrado.</span>  
<% end %>

app/views/carts/_new.html.erb
<header>
  <h1>Seu carrinho</h1>
  <% if @cart.present? %>
    <div id="cart">
      <div class="row">
        <% @cart.orders.each do |order| %>
          <% product = order.product %>         
          <div class="col-md-12 mt-5">
            <div class="card" style="width: 100%;">
              <div class="row">
                <div class="col-md-6">
                  <div class="row no-gutters">
                    <div class="col-md-4">
                      <% if product&.image.present? %>
                        <%= image_tag product.image.variant(:thumb).processed, class: "card-img", alt: "Imagem de capa do card" %>
                      <% else %>
                        <%= image_tag "default_image.jpeg", class: "card-img", alt: "Imagem de capa do card" %>  
                      <% end %>  
                    </div>
                    <div class="col-md-8">
                      <div class="card-body">
                        <% if product.present? %>
                          <h5 class="card-title"><%= product.name %></h5>
                          <p class="card-text"><%= product.description %></p>
                          <p class="card-text">Quantidade: <%= order.quantity %></p>
                          <% if product.price.present? %>
                            <p class="card-text">Preço unitário: R$<%= product.price %></p>
                          <% else %>
                            <p class="card-text text-danger">Preço não disponível</p>
                          <% end %>
                          <p class="card-text">                          
                            <%= button_to "Remover", remove_cart_item_cart_path(orders_id: order.id), method: :post, remote: true, class: "btn btn-outline-danger btn-sm", type: :submit %>
                          </p>
                        <% else %>
                          <p class="card-text text-danger">Produto não encontrado</p>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="card">
                    <div class="card-body">
                      <h5 class="card-title">Resumo do Pedido</h5>
                      <p class="card-text">Total: <%= @cart.total_price %></p>                       
                      <% if @addresses.present? %>                      
                        <% if @address.persisted? %>
                          <%= link_to "Endereço", address_path(@address), class: "btn btn-outline-secondary", data: { action: "click->carts#showAddresses" } %>
                        <% else %>              
                          <%= link_to "Novo Endereço", new_address_path, class: "btn btn-outline-secondary" %>
                        <% end %>
                        <%= turbo_stream.replace "addresses" do %>
                          <%= render partial: "carts/address_table", locals: { addresses: @addresses } %>
                        <% end %>
                      <% else %>                      
                        <%= link_to "Novo endereço", new_address_path, class: "btn btn-outline-secondary" %>
                        <%= turbo_stream.replace "new_address_form" do %>
                          <%= render partial: "carts/new_address_form", locals: { address: @address } %>
                        <% end %>
                      <% end %>
                      <%= link_to "Pagamento", new_order_path(@cart), class: "btn btn-outline-primary" %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>  
  <% else %>
    <p>Seu carrinho está vazio.</p>
  <% end %>
</header>

app/views/carts/_new_address_form.html.erb
<%= link_to "Novo endereço", new_address_path, class: "btn btn-primary" %>
  <% if @address.present? %>
    <%= simple_form_for @address, data: { turbo: false } do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
      <div class="form-inputs">
        <div class="row">
          <div class="col">
            <%= f.input :name, label: "Nome" %>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <%= f.input :street, label: "Rua" %>
          </div>
          <div class="col">
            <%= f.input :number, label: "Número" %>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <%= f.input :neighborhood, label: "Bairro" %>
          </div>
          <div class="col">
            <%= f.input :address_detail, label: "Complemento" %>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <%= f.input :zipcode, label: "CEP" %>
          </div>
          <div class="col">
            <%= f.input :city, label: "Cidade" %>
          </div>
          <div class="col">
            <%= f.input :state, label: "Estado" %>
          </div>
        </div>
      </div>
      <div class="form-actions mt-2">
        <%= f.button :submit, "Salvar", class: "btn btn-primary" %>
      </div> 
  <% end %>
<% end %>

app/views/carts/show.html.erb
<header>
  <h1>Seu carrinho</h1>
  <% if @cart.present? %>
    <div class="row">
      <% @cart.orders.each do |orders| %>
        <% product = orders.product %>
        <div class="col-md-12 mt-5">
          <div class="card" style="width: 100%;">
            <div class="row">
              <div class="col-md-6">
                <div class="row no-gutters">
                  <div class="col-md-4">
                    <% if product&.image.present? %>
                      <%= image_tag product.image.variant(:thumb).processed, class: "card-img", alt: "Imagem de capa do card" %>
                    <% else %>
                      <%= image_tag "default_image.jpeg", class: "card-img", alt: "Imagem de capa do card" %>  
                    <% end %>  
                  </div>
                  <div class="col-md-8">
                    <div class="card-body">
                      <% if product.present? %>
                        <h5 class="card-title"><%= product.name %></h5>
                        <p class="card-text"><%= product.description %></p>
                        <p class="card-text">Quantidade: <%= orders.quantity %></p>
                        <% if product.price.present? %>
                          <p class="card-text">Preço unitário: R$<%= product.price %></p>
                        <% else %>
                          <p class="card-text text-danger">Preço não disponível</p>
                        <% end %>
                        <p class="card-text">
                          <%= button_to "Atualizar", update_cart_cart_path(orders_id: orders.id), method: :post, remote: true, class: "btn btn-outline-secondary btn-sm", type: :submit %>
                          <%= button_to "Remover", remove_cart_item_cart_path(orders_id: orders.id), method: :post, remote: true, class: "btn btn-outline-danger btn-sm", type: :submit %>
                        </p>
                      <% else %>
                        <p class="card-text text-danger">Produto não encontrado</p>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="card">
                  <div class="card-body">
                    <h5 class="card-title">Resumo do Pedido</h5>
                    <p class="card-text">Total: <%= @cart.total_price %></p>                       
                    <% if @addresses.present? %>                      
                      <% if @address.persisted? %>
                        <%= link_to "Endereço", address_path(@address), class: "btn btn-outline-secondary", data: { action: "click->carts#showAddresses" } %>
                      <% else %>              
                        <%= link_to "Novo Endereço", new_address_path, class: "btn btn-outline-secondary" %>
                      <% end %>
                      <%= turbo_stream.replace "addresses" do %>
                        <%= render partial: "carts/address_table", locals: { addresses: @addresses } %>
                      <% end %>
                    <% else %>                      
                      <%= link_to "Novo endereço", new_address_path, class: "btn btn-outline-secondary" %>
                      <%= turbo_stream.replace "new_address_form" do %>
                        <%= render partial: "carts/new_address_form", locals: { address: @address } %>
                      <% end %>
                    <% end %>
                    <%= link_to "Pagamento", new_order_path(@cart), class: "btn btn-outline-primary" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <p>Seu carrinho está vazio.</p>
  <% end %>
</header>

app/views/carts/show_items.html.erb
<div id="cart">
  <turbo-frame id="cart-frame">
    <%= render "carts/new" %>
  </turbo-frame>
</div>