config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "home#index"
  resources :settings, only: [:index] do
    collection do
      get :orders
      get :password
      patch :update_user
      patch :update_password
    end
  end

  resources :orders, only: [:new, :create, :show, :index]

  resources :addresses
  resources :carts, only: [:show, :create] do
    member do
      post "add_to_cart", to: "carts#add", as: "add_to_cart"
      post "update_cart", to: "carts#update_item", as: "update_cart"
      post "remove_from_cart", to: "carts#remove", as: "remove_cart_item"
      post "finalize_order", to: "orders#finalize", as: "finalize_order"
      get "show_items", to: "carts#show_items", as: "show_items"
    end
    collection do
      post :create
    end
  end

  namespace :admin do
    root to: "dashboard#index"
    resources :categories
    resources :products
    resources :users do
      member do
        post :toggle_admin
      end
    end
  end
end

=begin
 em controllers de MVC existe três tipos de actions(por deaful):
  - actions de coleção: index, new, create
  - actions de membro: show, edit, update, destroy 


  estudar sobre "soft delete"
=end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/views/admin_users/_admin_user.html.erb
<div id="<%= dom_id admin_user %>">
</div>

app/views/admin_users/_form.html.erb
<%= simple_form_for(@admin_user) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin_users/edit.html.erb
<h1>Editing admin user</h1>

<%= render "form", admin_user: @admin_user %>

<br>

<div>
  <%= link_to "Show this admin user", @admin_user %> |
  <%= link_to "Back to admin users", admin_users_path %>
</div>

app/views/admin_users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Admin users</h1>

<div id="admin_users">
  <% @admin_users.each do |admin_user| %>
    <%= render admin_user %>
    <p>
      <%= link_to "Show this admin user", admin_user %>
    </p>
  <% end %>
</div>

<%= link_to "New admin user", new_admin_user_path %>

app/views/admin_users/new.html.erb
<h1>New admin user</h1>

<%= render "form", admin_user: @admin_user %>

<br>

<div>
  <%= link_to "Back to admin users", admin_users_path %>
</div>

app/views/admin_users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @admin_user %>

<div>
  <%= link_to "Edit this admin user", edit_admin_user_path(@admin_user) %> |
  <%= link_to "Back to admin users", admin_users_path %>

  <%= button_to "Destroy this admin user", @admin_user, method: :delete %>
</div>